{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMzluaupDDQxBImdBLKVDWB"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","source":["---\n","<h1 align='center'><b>ADVANCE PROGRAMMING ASSIGNMENT NO.6</b>\n","</h1>\n","\n","---"],"metadata":{"id":"-wFolL3C4r3j"}},{"cell_type":"markdown","source":["<h4 align='justify'><b>Q1. Describe three applications for exception processing.</b></h4>\n","<h4 align='justify'><b>try_except_else block:</b>\n","<h4 align='justify'>The try block lets you test a block of code for errors. The except block lets handle the error.The else block lets you execute when there is no error.</h4>\n","\n","```\n","try:\n","  # block of code\n","except Exceptions:\n","  # block of code\n","else:\n","  # This code execuions when execption is not occurs.\n","```"],"metadata":{"id":"TmFqBxTi4rou"}},{"cell_type":"code","source":["try:\n","  num = int(input(\"enter a number: \"))\n","  assert num%2 == 0\n","except:\n","  print(\"Not an even number.\")\n","else:\n","  reciprocal = 1/num\n","  print(reciprocal)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"gbwcvJNq5uTx","executionInfo":{"status":"ok","timestamp":1672066179067,"user_tz":-330,"elapsed":5163,"user":{"displayName":"Govind Devke","userId":"08858532865274458695"}},"outputId":"6b4a7271-180b-41ac-e55c-933950c958e3"},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["enter a number: 7\n","Not an even number.\n"]}]},{"cell_type":"markdown","source":["<h4 align='justify'><b>Q2. What happens if you don&#39;t do something extra to treat an exception?</b></h4>\n","<h4 align='justify'>An exeption object is created when a Python script raises an exeception. If the script explicitly doesn't handle the exeception, the program will be forced to terminate abruptly.</h4>"],"metadata":{"id":"Kb2fxw9s58uH"}},{"cell_type":"markdown","source":["<h4 align='justify'><b>Q3. What are your options for recovering from an exception in your script?</b></h4>\n","<h4 align='justify'>You can also provide a generic except clause, which handles any exception. After the except clause(s), you can handle an else-clause. The code in the else-block executes if the code in the try block does not raise an exception. The else-block is a good place for code that does not need the try: block's protection.</h4>"],"metadata":{"id":"9zxUSymE5_ne"}},{"cell_type":"markdown","source":["<h4 align='justify'><b>Q4. Describe two methods for triggering exceptions in your script.</b></h4>\n","<h4 align='justify'>To avoid a scenario, there are two methods to handle Python execeptions:<b> Try - This method catches the exceptions raised by the program. Raise - Triggers an exception manually using custom exceptions.</b></h4>"],"metadata":{"id":"h5kapGeC6Ebm"}},{"cell_type":"markdown","source":["<h4 align='justify'><b>Q5. Identify two methods for specifying actions to be executed at termination time, regardless of whether or not an exception exists.</b></h4>\n","<h4 align='justify'><b>Try and Except Statement - Catching Exceptions</b></h4>\n","<h4 align='justify'>In Python, we catch exceptions and handle them using try and except code blocks. The try clause contains the code that can raise an exception, while the except clause contains the code lines that handle the exception. Let's see if we can access the index from the array, which is more than the array's length, and handle the resulting exception.</h4>"],"metadata":{"id":"CX-8zE9t6Gul"}}]}